#pragma once

#include "tokki_gestures.h"

extern const tokki_action_descriptor_t TOKKI_SPEAKER_DRINK_WATER_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_CHIRP_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_ALERT_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_CHIME_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_PING_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_BUBBLE_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_WHISTLE_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_SIGH_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_BOING_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_QUESTION_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_DOWNSTEP_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_SPARKLE_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_TRILL_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_BARK_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_KNOCK_ACTION;
extern const tokki_action_descriptor_t TOKKI_SPEAKER_SONAR_ACTION;