#pragma once

#include "tokki_gestures.h"

extern const tokki_action_descriptor_t TOKKI_OLED_HAPPY_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_SAD_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_SURPRISED_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_BLINK_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_CURIOUS_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_DRINK_WATER_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_WATER_DROP_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_FIRE_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_WINK_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_CHECKMARK_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_THINKING_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_LOOK_LEFT_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_LOOK_RIGHT_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_LOOK_UP_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_LOOK_DOWN_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_SLEEPY_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_HEART_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_EXCLAMATION_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_LOVEY_DOVEY_ACTION;
extern const tokki_action_descriptor_t TOKKI_OLED_SHY_ACTION;