#pragma once

#include "esp_err.h"

typedef enum {
    TOKKI_SPEAKER_DRINK_WATER,
    TOKKI_SPEAKER_CHIRP,
    TOKKI_SPEAKER_ALERT,
    TOKKI_SPEAKER_CHIME,
    TOKKI_SPEAKER_PING,
    TOKKI_SPEAKER_DOG_BARK,
    TOKKI_SPEAKER_BUBBLE,
    TOKKI_SPEAKER_WHISTLE,
    TOKKI_SPEAKER_TONE_LOW,
    TOKKI_SPEAKER_TONE_MID,
    TOKKI_SPEAKER_QUESTION,
    TOKKI_SPEAKER_TONE_HIGH,
    TOKKI_SPEAKER_SPARKLE,
    TOKKI_SPEAKER_TRILL,
    TOKKI_SPEAKER_KNOCK,
    TOKKI_SPEAKER_SONAR,
    TOKKI_SPEAKER_TONE_RISE,
} tokki_speaker_sound_t;

esp_err_t tokki_speaker_play(tokki_speaker_sound_t sound);