#pragma once

#include "driver/gpio.h"
#include "esp_err.h"

#define TOKKI_BOARD_NEOPIXEL_GPIO GPIO_NUM_0
#define TOKKI_BOARD_PERIPHERAL_POWER_GPIO GPIO_NUM_2
#define TOKKI_BOARD_STATUS_LED_GPIO GPIO_NUM_13
#define TOKKI_BOARD_I2C_SCL_GPIO GPIO_NUM_20
#define TOKKI_BOARD_I2C_SDA_GPIO GPIO_NUM_22
#define TOKKI_BOARD_SPEAKER_BCLK_GPIO GPIO_NUM_27
#define TOKKI_BOARD_SPEAKER_DATA_GPIO GPIO_NUM_32
#define TOKKI_BOARD_SPEAKER_WS_GPIO GPIO_NUM_33

esp_err_t tokki_board_init(void);